on:
  release:
    types: [published]

jobs:
  build_ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: npm ci
        working-directory: ui

      - name: compile
        working-directory: ui
        # vite sets node_env=production automatically when building
        run: npm run build

      - name: package
        run: tar czvf draid.tar.gz -C ui dist -C ../examples init.sql nginx.app.conf nginx.service

      - name: upload ui
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} minidsp-ui.tar.gz

      - name: upload install_script
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} examples/install.sh
  build_ui_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: npm ci
        working-directory: ui

      - name: compile
        working-directory: ui
        # vite sets node_env=production automatically when building
        run: npm run build

      - name: setup buildx docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: generate docker
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/danielhstahl/householdhelper-ui:${{ github.event.release.tag_name }} -f docker/ui.Dockerfile . --push

      #- name: publish docker
      #  run: |
      #    docker push ghcr.io/danielhstahl/householdhelper-ui:${{ github.event.release.tag_name }}

  build_draid_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      #- name: build musl
      #  working-directory: draid
      #  run: |
      #    curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz -o cross-x86_64-unknown-linux-gnu.tar.gz
      ###    tar -xvzf cross-x86_64-unknown-linux-gnu.tar.gz
      #    rustup update stable
      #    rustup target add x86_64-unknown-linux-musl
      #    ./cross build --release --target x86_64-unknown-linux-musl

      - name: setup buildx docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: generate docker
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/danielhstahl/householdhelper-draid:${{ github.event.release.tag_name }} -f docker/draid.Dockerfile . --push

      #- name: publish docker
      #  run: |
      #    docker push ghcr.io/danielhstahl/householdhelper-draid:${{ github.event.release.tag_name }}
